--- #YAML:1.0
name:                WebService-Kizasi
version:             v0.02
abstract:            A Perl Interface for the Kizasi Web Services
license:             ~
author:              
    - DAIBA, Keiichi <daiba@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    LWP:                           0
    Test::Base:                    0
    URI::Escape:                   0
    version:                       0
    XML::RSS::LibXML:              0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
